### ISSUE TITLE
NameError: uninitialized constant RailsPrelaunchSignup

### ISSUE THREAD

**Issue by ajmalafif** [RailsApps/rails-prelaunch-signup#15]
I had an installation issue but sorted that out. Now right after I did 

```
'bundle install'
```

 http://localhost:3000/ or local.dev (with Pow) gave me this error:

```
~/projects/rails/learn/market/config/routes.rb:1:in `<top (required)>'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:40:in `each'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:40:in `load_paths'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:16:in `reload!'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:26:in `block in updater'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/activesupport-3.2.8/lib/active_support/file_update_checker.rb:78:in `call'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/activesupport-3.2.8/lib/active_support/file_update_checker.rb:78:in `execute'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:27:in `updater'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application/finisher.rb:66:in `block in <module:Finisher>'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `run'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `each'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/application.rb:136:in `initialize!'
~/.rvm/gems/ruby-1.9.3-p194@market/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
~/projects/rails/learn/market/config/environment.rb:5:in `<top (required)>'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
~/.rvm/rubies/ruby-1.9.3-p194/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
~/projects/rails/learn/market/config.ru:3:in `block in <main>'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/builder.rb:4:in `instance_eval'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/builder.rb:4:in `initialize'
~/projects/rails/learn/market/config.ru:1:in `new'
~/projects/rails/learn/market/config.ru:1:in `<main>'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:50:in `eval'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:50:in `load_config'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:43:in `initialize'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:13:in `new'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/lib/nack/server.rb:13:in `run'
~/Library/Application Support/Pow/Versions/0.4.0/node_modules/nack/bin/nack_worker:4:in `<main>'  
```

I googled and stumbled upon 8 results with nothing obvious. I'm working on getting through this one and will share anything here.

**Comment by DanielKehoe** [comment]
Thanks for bringing this to my attention. I've corrected an error in the template where the application name was not set correctly in the config/routes.rb file. I've updated the template. Please try again and reopen the issue if the problem is unresolved.

**Comment by ajmalafif** [comment]
Just sharing feedback and for future reference, this has fixed the issue and the template works now. Thanks!

**Comment by DanielKehoe** [comment]
Great!
