### ISSUE TITLE
Tests are not running correctly after commit aa03a8951c

### ISSUE THREAD

**Issue by mdlima** [RailsApps/rails-prelaunch-signup#21]
Running tests for the second time after last commit will yield 5 validation errors in the users_controller_spec and user_mailer_spec:

```
Failures:

  1) UserMailer should be delivered to the email address provided
     Failure/Error: @user = FactoryGirl.create(:user, email: "example@example.com")
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
     # ./spec/mailers/user_mailer_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) UserMailer should contain the correct message in the mail body
     Failure/Error: @user = FactoryGirl.create(:user, email: "example@example.com")
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
     # ./spec/mailers/user_mailer_spec.rb:5:in `block (2 levels) in <top (required)>'

  3) UserMailer should have the correct subject
     Failure/Error: @user = FactoryGirl.create(:user, email: "example@example.com")
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
     # ./spec/mailers/user_mailer_spec.rb:5:in `block (2 levels) in <top (required)>'

  4) UsersController GET 'show' should be successful
     Failure/Error: @user = FactoryGirl.create(:user)
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
     # ./spec/controllers/users_controller_spec.rb:6:in `block (2 levels) in <top (required)>'

  5) UsersController GET 'show' should find the right user
     Failure/Error: @user = FactoryGirl.create(:user)
     ActiveRecord::RecordInvalid:
       Validation failed: Email has already been taken
     # ./spec/controllers/users_controller_spec.rb:6:in `block (2 levels) in <top (required)>'
```

Going through the last commit, I found that the DatabaseCleaner had been removed from the spec_helper.rb file. Changing the file to the previous version (https://github.com/RailsApps/rails-prelaunch-signup/blob/884c0d26a597d663b6775496893cb32f6c7a403d/spec/spec_helper.rb) solved the issue.

**Comment by DanielKehoe** [comment]
Marcio, Thanks for catching this. I've restored the missing DatabaseCleaner configuration.

-- Daniel

**Comment by mdlima** [comment]
No problem Daniel. Thanks for creating this project, I'm glad I could help.
