### ISSUE TITLE
Cucumber tests fail

### ISSUE THREAD

**Issue by mrichman** [RailsApps/rails-prelaunch-signup#37]
Are the cucumber tests supposed to work?

```
Using the default profile...
Feature: Send Invitations
  As the owner of the site
  I want to send invitations to visitors who have requested invitations
  so users can try the site

  Scenario: Administrator sends invitation                           # features/admin/send_invitations.feature:6
    Given I request an invitation with valid user data               # features/step_definitions/visitor_steps.rb:42
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/visitor_steps.rb:8:in `invitation_request'
      ./features/step_definitions/visitor_steps.rb:43:in `/^I request an invitation with valid user data$/'
      features/admin/send_invitations.feature:7:in `Given I request an invitation with valid user data'
    And I am logged in as an administrator                           # features/step_definitions/admin_steps.rb:1
    When I visit the users page                                      # features/step_definitions/admin_steps.rb:9
    And I click a link "send invitation"                             # features/step_definitions/admin_steps.rb:13
    And I open the email with subject "Confirmation instructions"    # features/step_definitions/email_steps.rb:80
    Then I should see "confirm your email address" in the email body # features/step_definitions/email_steps.rb:108

Feature: View Progress
  As the owner of the site
  I want to know how many visitors have requested invitations
  so I can know if my offer is popular

  Scenario: Administrator views list of users          # features/admin/view_progress.feature:6
    Given I request an invitation with valid user data # features/step_definitions/visitor_steps.rb:42
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/visitor_steps.rb:8:in `invitation_request'
      ./features/step_definitions/visitor_steps.rb:43:in `/^I request an invitation with valid user data$/'
      features/admin/view_progress.feature:7:in `Given I request an invitation with valid user data'
    And I am logged in as an administrator             # features/step_definitions/admin_steps.rb:1
    When I visit the users page                        # features/step_definitions/admin_steps.rb:9
    Then I should see a list of users                  # features/step_definitions/admin_steps.rb:17

  Scenario: User cannot view list of users     # features/admin/view_progress.feature:12
    Given I am logged in                       # features/step_definitions/user_steps.rb:50
    When I visit the users page                # features/step_definitions/admin_steps.rb:9
    Then I should see an access denied message # features/step_definitions/admin_steps.rb:21
      expected to find text "Not authorized as an administrator" in "Rails Prelaunch Signup Login Sign up × You need to sign in or sign up before continuing. Sign in Email Password Remember me Forgot your password?" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/admin_steps.rb:22:in `/^I should see an access denied message$/'
      features/admin/view_progress.feature:15:in `Then I should see an access denied message'

Feature: Sign in
  In order to get access to protected sections of the site
  A user
  Should be able to sign in

  Scenario: User is not signed up         # features/users/sign_in.feature:6
    Given I do not exist as a user        # features/step_definitions/user_steps.rb:59
    When I sign in with valid credentials # features/step_definitions/user_steps.rb:69
    Then I see an invalid login message   # features/step_definitions/user_steps.rb:177
    And I should be signed out            # features/step_definitions/user_steps.rb:139

  Scenario: User signs in successfully      # features/users/sign_in.feature:12
    Given I exist as a user                 # features/step_definitions/user_steps.rb:55
    And I am not logged in                  # features/step_definitions/user_steps.rb:46
    When I sign in with valid credentials   # features/step_definitions/user_steps.rb:69
    Then I see a successful sign in message # features/step_definitions/user_steps.rb:149
      expected to find text "Signed in successfully." in "Rails Prelaunch Signup Login Sign up × Invalid email or password. Sign in Email Password Remember me Forgot your password?" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/user_steps.rb:150:in `/^I see a successful sign in message$/'
      features/users/sign_in.feature:16:in `Then I see a successful sign in message'
    When I return to the site               # features/step_definitions/user_steps.rb:107
    Then I should be signed in              # features/step_definitions/user_steps.rb:133

  Scenario: User enters wrong email     # features/users/sign_in.feature:20
    Given I exist as a user             # features/step_definitions/user_steps.rb:55
    And I am not logged in              # features/step_definitions/user_steps.rb:46
    When I sign in with a wrong email   # features/step_definitions/user_steps.rb:111
    Then I see an invalid login message # features/step_definitions/user_steps.rb:177
    And I should be signed out          # features/step_definitions/user_steps.rb:139

  Scenario: User enters wrong password   # features/users/sign_in.feature:27
    Given I exist as a user              # features/step_definitions/user_steps.rb:55
    And I am not logged in               # features/step_definitions/user_steps.rb:46
    When I sign in with a wrong password # features/step_definitions/user_steps.rb:116
    Then I see an invalid login message  # features/step_definitions/user_steps.rb:177
    And I should be signed out           # features/step_definitions/user_steps.rb:139

Feature: Sign out
  To protect my account from unauthorized access
  A signed in user
  Should be able to sign out

  Scenario: User signs out                 # features/users/sign_out.feature:6
    Given I am logged in                   # features/step_definitions/user_steps.rb:50
    When I sign out                        # features/step_definitions/user_steps.rb:74
    Then I should see a signed out message # features/step_definitions/user_steps.rb:173
      expected to find text "Signed out successfully." in "Rails Prelaunch Signup Login Sign up Want in? Request invite" (RSpec::Expectations::ExpectationNotMetError)
      ./features/step_definitions/user_steps.rb:174:in `/^I should see a signed out message$/'
      features/users/sign_out.feature:9:in `Then I should see a signed out message'
    When I return to the site              # features/step_definitions/user_steps.rb:107
    Then I should be signed out            # features/step_definitions/user_steps.rb:139

Feature: Sign up
  In order to get access to protected sections of the site
  As a user
  I want to be able to sign up

  Background:                # features/users/sign_up.feature:6
    Given I am not logged in # features/step_definitions/user_steps.rb:46

  Scenario: User signs up with valid data          # features/users/sign_up.feature:9
    When I sign up with valid user data            # features/step_definitions/user_steps.rb:78
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/user_steps.rb:33:in `sign_up'
      ./features/step_definitions/user_steps.rb:80:in `/^I sign up with valid user data$/'
      features/users/sign_up.feature:10:in `When I sign up with valid user data'
    Then I should see a successful sign up message # features/step_definitions/user_steps.rb:153

  Scenario: User signs up with invalid email   # features/users/sign_up.feature:13
    When I sign up with an invalid email       # features/step_definitions/user_steps.rb:83
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/user_steps.rb:33:in `sign_up'
      ./features/step_definitions/user_steps.rb:86:in `/^I sign up with an invalid email$/'
      features/users/sign_up.feature:14:in `When I sign up with an invalid email'
    Then I should see an invalid email message # features/step_definitions/user_steps.rb:157

Feature: Edit User
  As a registered user of the website
  I want to edit my user profile
  so I can change my username

  Scenario: I sign in and edit my account       # features/users/user_edit.feature:6
    Given I am logged in                        # features/step_definitions/user_steps.rb:50
    When I edit my account details              # features/step_definitions/user_steps.rb:121
      Unable to find link "Edit account" (Capybara::ElementNotFound)
      ./features/step_definitions/user_steps.rb:122:in `/^I edit my account details$/'
      features/users/user_edit.feature:8:in `When I edit my account details'
    Then I should see an account edited message # features/step_definitions/user_steps.rb:181

Feature: Show Users
  As a visitor to the website
  I want to see registered users listed on the homepage
  so I can know if the site has users

Feature: Request Invitation
  As a visitor to the website
  I want to request an invitation 
  so I can be notified when the site is launched

  Background:                # features/visitors/request_invitation.feature:6
    Given I am not logged in # features/step_definitions/user_steps.rb:46

  Scenario: User views home page                    # features/visitors/request_invitation.feature:9
    When I visit the home page                      # features/step_definitions/visitor_steps.rb:12
    Then I should see a button "Request Invitation" # features/step_definitions/visitor_steps.rb:16
      expected to find button "Request Invitation" but there were no matches. Also found "", which matched the selector but not all filters. (Capybara::ExpectationNotMet)
      ./features/step_definitions/visitor_steps.rb:17:in `/^I should see a button "([^\"]*)"$/'
      features/visitors/request_invitation.feature:11:in `Then I should see a button "Request Invitation"'

  Scenario: User views invitation request form    # features/visitors/request_invitation.feature:13
    When I visit the home page                    # features/step_definitions/visitor_steps.rb:12
    And I click a button "Request Invitation"     # features/step_definitions/visitor_steps.rb:20
      Unable to find button "Request Invitation" (Capybara::ElementNotFound)
      ./features/step_definitions/visitor_steps.rb:21:in `/^I click a button "([^"]*)"$/'
      features/visitors/request_invitation.feature:15:in `And I click a button "Request Invitation"'
    Then I should see a form with a field "Email" # features/step_definitions/visitor_steps.rb:24

  Scenario: User signs up with valid data                 # features/visitors/request_invitation.feature:18
    When I request an invitation with valid user data     # features/step_definitions/visitor_steps.rb:42
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/visitor_steps.rb:8:in `invitation_request'
      ./features/step_definitions/visitor_steps.rb:43:in `/^I request an invitation with valid user data$/'
      features/visitors/request_invitation.feature:19:in `When I request an invitation with valid user data'
    Then I should see a message "Thank You"               # features/step_definitions/visitor_steps.rb:28
    And my email address should be stored in the database # features/step_definitions/visitor_steps.rb:32
    And my account should be unconfirmed                  # features/step_definitions/visitor_steps.rb:37

  Scenario: User signs up with invalid email           # features/visitors/request_invitation.feature:24
    When I request an invitation with an invalid email # features/step_definitions/visitor_steps.rb:46
      Unable to find field "Email" (Capybara::ElementNotFound)
      ./features/step_definitions/visitor_steps.rb:8:in `invitation_request'
      ./features/step_definitions/visitor_steps.rb:48:in `/^I request an invitation with an invalid email$/'
      features/visitors/request_invitation.feature:25:in `When I request an invitation with an invalid email'
    Then I should see an invalid email message         # features/step_definitions/user_steps.rb:157

Failing Scenarios:
cucumber features/admin/send_invitations.feature:6 # Scenario: Administrator sends invitation
cucumber features/admin/view_progress.feature:6 # Scenario: Administrator views list of users
cucumber features/admin/view_progress.feature:12 # Scenario: User cannot view list of users
cucumber features/users/sign_in.feature:12 # Scenario: User signs in successfully
cucumber features/users/sign_out.feature:6 # Scenario: User signs out
cucumber features/users/sign_up.feature:9 # Scenario: User signs up with valid data
cucumber features/users/sign_up.feature:13 # Scenario: User signs up with invalid email
cucumber features/users/user_edit.feature:6 # Scenario: I sign in and edit my account
cucumber features/visitors/request_invitation.feature:9 # Scenario: User views home page
cucumber features/visitors/request_invitation.feature:13 # Scenario: User views invitation request form
cucumber features/visitors/request_invitation.feature:18 # Scenario: User signs up with valid data
cucumber features/visitors/request_invitation.feature:24 # Scenario: User signs up with invalid email

15 scenarios (12 failed, 3 passed)
62 steps (12 failed, 20 skipped, 30 passed)
0m2.773s
rake aborted!
Command failed with status (1): [/home/mrichman/.rvm/rubies/ruby-2.0.0-p0/b...]
```

**Comment by DanielKehoe** [comment]
The test suite is a work in progress (unfinished as of now). Pull requests welcomed if you can contribute fixes!

**Comment by cpjobling** [comment]
Could the issue be with the Ajax version of the sign-in page?

**Comment by DanielKehoe** [comment]
@tmock12 contributed improved tests so this issue should now be resolved. Please reopen if there are any further problems with Cucumber tests.
